# Generated by Django 2.0.5 on 2019-01-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='员工', max_length=10, verbose_name='角色'),
        ),
    ]
